/* ============================= AssetManager ============================== */
/* No runtime HTTP loading. Images are either drawn procedurally onto an
   offscreen canvas (used by this demo, so the framework needs zero binary
   assets to run) or registered directly from an embedded base64 string -
   the recommended path once real artwork is ready. Both are safe on file://. */
class AssetManager {
  constructor() {
    this.images = {};
    this.sounds = {};
    this.spriteSheets = {};
  }
  // Register an image generated by drawing into an offscreen canvas.
  registerImage(key, drawFn, w = 128, h = 128) {
    const c = document.createElement('canvas');
    c.width = w; c.height = h;
    drawFn(c.getContext('2d'), w, h);
    this.images[key] = c;
    return c;
  }
  // Register an image from an embedded base64 data URI (e.g. "data:image/png;base64,....").
  registerImageBase64(key, base64) {
    const img = new Image();
    img.src = base64;
    this.images[key] = img;
    return img;
  }
  getImage(key) { return this.images[key]; }

  registerSpriteSheet(key, canvasOrImage, frameW, frameH, frameCount) {
    this.spriteSheets[key] = { canvas: canvasOrImage, frameW, frameH, frameCount };
  }
  getSpriteSheet(key) { return this.spriteSheets[key]; }

  registerSound(key, generatorFn) { this.sounds[key] = generatorFn; }
  getSound(key) { return this.sounds[key]; }
}
